# Generated by Django 3.2.8 on 2021-10-09 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20211009_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='post1',
            name='slug',
            field=models.SlugField(default=posts.models.generate_id, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='post1',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
    ]
