# Generated by Django 3.2.6 on 2021-10-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post1',
            name='caption',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
