# Generated by Django 3.2.6 on 2021-10-09 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_tree'),
        ('posts', '0005_alter_post1_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='post1',
            name='drive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.drive'),
        ),
    ]
