# Generated by Django 3.2.6 on 2021-10-09 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_tree'),
        ('posts', '0006_post1_drive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post1',
            name='drive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.drive'),
        ),
        migrations.AlterField(
            model_name='post1',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
