# Generated by Django 3.2.6 on 2021-10-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20211009_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post1',
            name='photo',
            field=models.FileField(upload_to='posts_photo'),
        ),
    ]
