# Generated by Django 3.2.6 on 2021-10-06 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='members',
            field=models.ManyToManyField(related_name='mebers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='drive',
            name='host',
        ),
        migrations.AddField(
            model_name='drive',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hostedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Planter',
        ),
    ]
