# Generated by Django 3.2.6 on 2021-10-08 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20211008_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='members',
            field=models.ManyToManyField(related_name='mebers', to=settings.AUTH_USER_MODEL),
        ),
    ]
