# Generated by Django 3.2.6 on 2021-10-08 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_drive_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_count', models.IntegerField()),
                ('drive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.drive')),
            ],
        ),
    ]
