# Generated by Django 3.2.6 on 2021-10-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_drive_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
