# Generated by Django 3.2.6 on 2021-10-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_post'),
        ('users', '0008_drive_count'),
    ]

    operations = [
    ]
