# Generated by Django 3.2.6 on 2021-10-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_0003_delete_post_0008_drive_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tree',
        ),
    ]
