# Generated by Django 3.2.6 on 2021-10-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='indi_tree_count',
            field=models.IntegerField(default=0),
        ),
    ]
